redirectsOrigin = "config"
plugins = []
functionsDirectory = "/home/kalyanak/ionic/shop/netlify/functions"
functionsDirectoryOrigin = "config-v1"
headers = []

[functions]

[functions."*"]
included_files = ["routes/**"]
node_bundler = "esbuild"

[build]
publish = "/home/kalyanak/ionic/shop"
publishOrigin = "default"
functions = "/home/kalyanak/ionic/shop/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/api/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]