plugins = []
functionsDirectory = "/home/kalyanak/ionic/shop/functions"
functionsDirectoryOrigin = "config-v1"
headers = []
redirects = []

[dev]
functions = "functions"

[functions]

[functions."*"]

[build]
publish = "/home/kalyanak/ionic/shop"
publishOrigin = "config"
functions = "/home/kalyanak/ionic/shop/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]