[functions]
  node_bundler = "esbuild"
  included_files = ["routes/**"]
  
[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/api/:splat"
  status = 200